# Profile information
name: Hugh Ferguson
title: Hugh Ferguson
description: > # this means to ignore newlines until "baseurl:"
  A place for my ideas, projects, and current endeavors. 
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social
linkedin: hughferg
github: HughFerg

# Contact form
email: hughferguson25@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
